#include "tileset.h"

#define B4(k) k, k, k, k
#define B16(k) B4(k), B4(k), B4(k), B4(k)
#define PORTAL(k) GT_NONE, k, GT_NONE

const uint8_t gs_tile_info[T_LEVEL_COUNT] = {
    GT_NONE,
    B16(GT_BLOCK),
    B4(GT_SLAB_LO),
    B4(GT_SLAB_HI),
    GT_SPIKE_UP, GT_SPIKE_DOWN, GT_SPIKE_SM_UP, GT_SPIKE_SM_DOWN,
    GT_SAW_SMALL,
    GT_ORB_YELLOW, GT_ORB_PINK, GT_ORB_BLUE, GT_ORB_GREEN,
    GT_PAD_YELLOW, GT_PAD_PINK, GT_PAD_BLUE,
    GT_PAD_YELLOW | GTI_CEILING, GT_PAD_PINK | GTI_CEILING, GT_PAD_BLUE | GTI_CEILING,
    PORTAL(GT_PORTAL_CUBE), PORTAL(GT_PORTAL_SHIP), PORTAL(GT_PORTAL_BALL), PORTAL(GT_PORTAL_UFO),
    PORTAL(GT_PORTAL_WAVE), PORTAL(GT_PORTAL_FLIP), PORTAL(GT_PORTAL_NORMAL),
    PORTAL(GT_SPEED_0), PORTAL(GT_SPEED_1), PORTAL(GT_SPEED_2), PORTAL(GT_SPEED_3),
    GT_COIN, GT_COIN | (1 << 5), GT_COIN | (2 << 5), GT_COIN | (3 << 5),
    GT_NONE, GT_NONE, GT_NONE, GT_NONE, GT_NONE, GT_NONE, GT_NONE, GT_NONE, /* scenery */
};
