#include "tileset.h"

#define B4(k) k, k, k, k
#define B16(k) B4(k), B4(k), B4(k), B4(k)
#define PORTAL(k) OBJ_NONE, k, OBJ_NONE

const uint8_t gs_tile_info[T_LEVEL_COUNT] = {
    OBJ_NONE,
    B16(OBJ_BLOCK),
    B4(OBJ_SLAB_LO),
    B4(OBJ_SLAB_HI),
    OBJ_SPIKE_UP, OBJ_SPIKE_DOWN, OBJ_SPIKE_SM_UP, OBJ_SPIKE_SM_DOWN,
    OBJ_SAW_SMALL,
    OBJ_ORB_YELLOW, OBJ_ORB_PINK, OBJ_ORB_BLUE, OBJ_ORB_GREEN,
    OBJ_PAD_YELLOW, OBJ_PAD_PINK, OBJ_PAD_BLUE,
    OBJ_PAD_YELLOW | GTI_CEILING, OBJ_PAD_PINK | GTI_CEILING, OBJ_PAD_BLUE | GTI_CEILING,
    PORTAL(OBJ_PORTAL_CUBE), PORTAL(OBJ_PORTAL_SHIP), PORTAL(OBJ_PORTAL_BALL), PORTAL(OBJ_PORTAL_UFO),
    PORTAL(OBJ_PORTAL_WAVE), PORTAL(OBJ_PORTAL_GRAV_FLIP), PORTAL(OBJ_PORTAL_GRAV_NORMAL),
    PORTAL(OBJ_SPEED_0), PORTAL(OBJ_SPEED_1), PORTAL(OBJ_SPEED_2), PORTAL(OBJ_SPEED_3),
    OBJ_COIN, OBJ_COIN | (1 << 5), OBJ_COIN | (2 << 5), OBJ_COIN | (3 << 5),
    OBJ_NONE, OBJ_NONE, OBJ_NONE, OBJ_NONE, OBJ_NONE, OBJ_NONE, OBJ_NONE, OBJ_NONE, /* scenery */
    OBJ_NONE, OBJ_NONE, OBJ_NONE, OBJ_NONE, OBJ_NONE, /* the finish line */
};
