/*
 * gba_tool - makes the Game Boy Advance ROM's data from the game itself.
 *
 *   gba_tool export <dir>     write build/gba/gen: the graphics, drawn by the
 *                             core's renderer (gba_art.c), and the songs and
 *                             sound effects, played by the core's synthesizer
 *                             (gba_audio.c), as the ROM's data
 *   gba_tool audiocheck       make every song and sound as the ROM has them
 *                             and report how close its 8-bit samples come to
 *                             the synth (fails if any falls below the bar)
 *   gba_tool artsheet <png>   the level's cells, the ground's tiles and the
 *                             squares behind, magnified, to look at
 *   gba_tool objsheet <png>   the sprites, in each palette, magnified
 *
 * Makefile.gba runs `export` before building the ROM.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "gba_gen.h"
#include "../core/platform.h"

/* the core's save functions, which the tool never calls */
int plat_save_read(void *buf, int size) { (void)buf; (void)size; return -1; }
int plat_save_write(const void *buf, int size) { (void)buf; (void)size; return 0; }
const char *plat_name(void) { return "gba_tool"; }

void gba_gen_blob(GbaGen *g, const char *name, const char *ctype, const void *data, size_t bytes)
{
    char path[1024];
    if (!g->dir) return; /* drawing a sheet: nothing is written */
    snprintf(path, sizeof(path), "%s/%s.bin", g->dir, name);
    FILE *f = fopen(path, "wb");
    if (!f || (bytes && fwrite(data, 1, bytes, f) != bytes)) {
        fprintf(stderr, "gba_tool: can't write %s\n", path);
        exit(1);
    }
    fclose(f);
    fprintf(g->data_s, "    .global %s\n    .balign 4\n%s:\n    .incbin \"%s.bin\"\n", name, name, name);
    fprintf(g->hdr, "extern const %s %s[]; /* %zu bytes */\n", ctype, name, bytes);
    g->blob_bytes += bytes;
}

static FILE *open_out(const char *dir, const char *name)
{
    char path[1024];
    snprintf(path, sizeof(path), "%s/%s", dir, name);
    FILE *f = fopen(path, "w");
    if (!f) {
        fprintf(stderr, "gba_tool: can't write %s\n", path);
        exit(1);
    }
    return f;
}

static int cmd_export(const char *dir)
{
    GbaGen g;
    memset(&g, 0, sizeof(g));
    g.dir = dir;
    g.data_s = open_out(dir, "data.s");
    g.hdr = open_out(dir, "gen.h");
    g.src = open_out(dir, "gen.c");
    fprintf(g.data_s, "@ generated by gba_tool: the ROM's graphics and sound\n    .section .rodata\n");
    fprintf(g.hdr, "/* generated by gba_tool: the ROM's graphics and sound */\n#ifndef PD_GBA_GEN\n#define PD_GBA_GEN\n#include <stdint.h>\n");
    fprintf(g.src, "/* generated by gba_tool */\n#include \"gen.h\"\n");
    int err = gba_art_export(&g) || gba_levels_export(&g) || gba_audio_export(&g);
    fprintf(g.hdr, "#endif\n");
    fclose(g.data_s);
    fclose(g.hdr);
    fclose(g.src);
    if (!err) printf("gba_tool: %zu KB of data in %s\n", g.blob_bytes / 1024, dir);
    return err;
}

int gba_audio_check(void);
int gba_art_sheet(const char *out);
int gba_art_obj_sheet(const char *out);

int main(int argc, char **argv)
{
    if (argc >= 3 && !strcmp(argv[1], "export")) return cmd_export(argv[2]);
    if (argc >= 2 && !strcmp(argv[1], "audiocheck")) return gba_audio_check();
    if (argc >= 3 && !strcmp(argv[1], "artsheet")) return gba_art_sheet(argv[2]);
    if (argc >= 3 && !strcmp(argv[1], "objsheet")) return gba_art_obj_sheet(argv[2]);
    fprintf(stderr, "usage: gba_tool export <dir> | audiocheck | artsheet|objsheet <out.png>\n");
    return 2;
}
